// Fill out your copyright notice in the Description page of Project Settings.
#pragma once
#include "NativeGameplayTags.h"
namespace WarriorGameplayTags
{
	/** Input Tags **/
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	/**Player Weapon Tag**/
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);


	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	//Enemy
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);

	//Shared Tags
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	KNIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);


}